---
---
= Enterprise Environments
Veer Muchandi, Erik Jacobs, Trevor Quinn <tquinn@redhat.com>
v2.0, 2015-10-19
:scripts_repo: https://github.com/rhtconsulting/rhc-ose
:toc: macro
:toc-title:

toc::[]

There are at least three considerations for enterprise environments:

== Disconnected Environments

=== Assumptions

This document assumes that you understand the overall architecture of OpenShift 3 and that you have already planned out what the topology of your environment will look like. If you do not have a thorough understanding of the architecture of OpenShift 3, the service layer, projects, and how topologies are configured via the scheduler, there are steps in this document that may not make sense. For more information, see https://docs.openshift.com/enterprise/3.0/architecture/overview.html[OSE 3 Architecture Overview]. This document also assumes that you have some understanding of Docker, registries, and Docker’s command line tools.

=== Required Software and Components

It is frequently the case that portions of a datacenter environment may not have any access to the internet, even via proxy servers. Installing OpenShift in these environments is considered a “disconnected installation”.

An OpenShift Enterprise disconnected installation differs from a regular installation two primary ways:

. *Access to OpenShift Software Channels/Repos:* The OpenShift software channels will not be available via Red Hat’s content distribution network. Usually customers in such situations have a Satellite server that provides access to Red Hat content via the intranet/LAN. But, in some cases, there may not be a Satellite.

. *Access to OpenShift Dockerized Components:* OpenShift uses several Dockerized components. Normally these images are pulled directly from Red Hat’s Docker registry. In a disconnected environment, this is not possible.

This document details providing access to the OpenShift software when Satellite is not available in the environment. For environments with Satellite, it is assumed that someone can synchronize the OpenShift software into the Satellite for use with the OpenShift servers. Once the OpenShift software is made available to the relevant servers, the installation process is the same as a standard “connected” installation.

This document additionally details manually downloading the Docker images and how to transport them onto the relevant servers. Satellite 6.1 introduces the ability to act as a Docker registry, and it can be used to host the OpenShift dockerized components. Doing so is outside of scope for this document.

Once installed, in order to use OpenShift, you will need source code in a source control repository (current Git). We assume that an internal git repository is available that can host source code and this repository is accessible from the OpenShift nodes. Installing the source control repository is out of scope of this document.

Also when you try to build applications in OpenShift, your build may have some external dependencies such as a Maven Repository or Gem files (for Ruby). By default, the docker images provided by RedHat try to reach out to external repositories on internet. You can configure to use your own internal repositories. For the purposes of this document, we assume that such internal repositories already exist and are accessible from the OpenShift nodes. Installing such repositories is outside the scope of this document.

=== Software and Docker Image Preparation

In order to pull down the required software repositories and Docker images, you will need a RHEL7 server with access to the internet and at least 100GB of additional free space. All steps in this section should be performed on the internet-connected server. It is assumed that all steps will be performed as the root system user.

==== Syncing Repositories

First, register the server with Red Hat’s customer portal. You will need to use the login and password associated with the account that has access to the OpenShift subscriptions.

    subscription-manager register

Next, you will need to attach to a subscription that provides OpenShift channels. You can find the list of available subscriptions using:

    subscription-manager list --available

Find the pool ID for the subscription that provides OpenShift, and then:

    subscription-manager attach --pool=${pool_id}
    subscription-manager repos --disable="*"
    subscription-manager repos \
        --enable="rhel-7-server-rpms" \
        --enable="rhel-7-server-extras-rpms" \
        --enable="rhel-7-server-optional-rpms" \
        --enable="rhel-7-server-ose-3.0-rpms"

You will additionally need to install and configure the EPEL repository. Currently the OpenShift installer is Ansible-based, and Ansible is provided in the EPEL repository. You will synchronize only a select few packages from EPEL.

    yum -y install \
    http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm

Lastly, yum-utils provides “reposync” which lets you mirror yum repositories, and createrepo can create a “usable” yum repository from a directory.

    yum -y install yum-utils createrepo docker git

You will need up to 110GB of free space in order to sync the software. Depending on how restrictive your organization’s policies are, you could re-connect this server to the disconnected LAN and use it as the repository server. You could use USB-connected storage and transport the software to another server that will act as the repository server. There are even more options, but this document only covers these first two.

Make a path to where you want to sync the software (either locally or on your USB or other device):

    mkdir -p /path/to/repos

Now sync the packages and create the repo for each of them. Note you will need to modify the command for the appropriate path you created above.

    for repo in \
    rhel-7-server-rpms rhel-7-server-extras-rpms \
    rhel-7-server-optional-rpms rhel-7-server-ose-3.0-rpms
    do
      reposync --gpgcheck -lmn --repoid=${repo} --download_path=/path/to/repos
      createrepo -v /path/to/repos/${repo}
    done

Create a folder for EPEL and then sync the necessary packages:

    mkdir /path/to/repos/epel
    SOME_WGET_OR_OTHER_STEPS
    createrepo -v /path/to/repos/epel

Lastly, you will need to download the installation source repository. This can be done as follows:

    cd /path/to/repos
    git clone https://github.com/openshift/openshift-ansible

==== Syncing Images

Start the Docker daemon:

    systemctl start docker

The next commands will pull all of the required OpenShift dockerized components:

    docker pull registry.access.redhat.com/openshift3/ose-haproxy-router
    docker pull registry.access.redhat.com/openshift3/ose-deployer
    docker pull registry.access.redhat.com/openshift3/ose-sti-builder
    docker pull registry.access.redhat.com/openshift3/ose-docker-builder
    docker pull registry.access.redhat.com/openshift3/ose-pod
    docker pull registry.access.redhat.com/openshift3/ose-docker-registry

The next commands will pull Red Hat’s certified Source-to-Image (S2I) builder images. Source-to-Image (S2I) is the process that OpenShift uses to take application code and build it into a Docker image to run on the platform. More information about S2I can be found here:

link:../AppDev/builds.adoc[OpenShift Playbooks: Builds]

If there are any languages, runtimes or databases that you do not wish to use, you can skip them.

.Feedback or Contribution Needed
****
Need to verify version numbers below
****

    docker pull registry.access.redhat.com/jboss-amq-6/amq-openshift
    docker pull registry.access.redhat.com/jboss-eap-6/eap-openshift
    docker pull registry.access.redhat.com/jboss-webserver-3/tomcat7-openshift
    docker pull registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift
    docker pull registry.access.redhat.com/openshift3/mongodb-24-rhel7
    docker pull registry.access.redhat.com/openshift3/mysql-55-rhel7
    docker pull registry.access.redhat.com/openshift3/nodejs-010-rhel7
    docker pull registry.access.redhat.com/openshift3/perl-516-rhel7
    docker pull registry.access.redhat.com/openshift3/php-55-rhel7
    docker pull registry.access.redhat.com/openshift3/postgresql-92-rhel7
    docker pull registry.access.redhat.com/openshift3/python-33-rhel7
    docker pull registry.access.redhat.com/openshift3/ruby-20-rhel7

==== Prepare Images for Export

Docker images may be exported from a system by first saving them to a tarball and then transporting them. Change to root’s home directory:

    mkdir /path/to/repos/images
    cd /path/to/repos/images

Export the OpenShift Dockerized components as follows:

    docker save -o ose3-images.tar \
    registry.access.redhat.com/openshift3/ose-haproxy-router \
    registry.access.redhat.com/openshift3/ose-deployer \
    registry.access.redhat.com/openshift3/ose-sti-builder \
    registry.access.redhat.com/openshift3/ose-docker-builder \
    registry.access.redhat.com/openshift3/ose-pod \
    registry.access.redhat.com/openshift3/ose-docker-registry

Export the S2I builder images as follows, making sure to remove any items that you did not sync in the previous section:

.Feedback or Contribution Needed
****
Need to verify version numbers below
****

    docker save -o ose3-builder-images.tar \
    registry.access.redhat.com/jboss-amq-6/amq-openshift \
    registry.access.redhat.com/jboss-eap-6/eap-openshift \
    registry.access.redhat.com/jboss-webserver-3/tomcat7-openshift \
    registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift \
    registry.access.redhat.com/openshift3/mongodb-24-rhel7 \
    registry.access.redhat.com/openshift3/mysql-55-rhel7 \
    registry.access.redhat.com/openshift3/nodejs-010-rhel7 \
    registry.access.redhat.com/openshift3/perl-516-rhel7 \
    registry.access.redhat.com/openshift3/php-55-rhel7 \
    registry.access.redhat.com/openshift3/postgresql-92-rhel7 \
    registry.access.redhat.com/openshift3/python-33-rhel7 \
    registry.access.redhat.com/openshift3/ruby-20-rhel7

=== Repository Server

During the installation (and for later updates, should you so choose) you will need a webserver to host the repositories. RHEL7 can provide the Apache webserver, and its installation and configuration are documented in the following steps.

==== Option 1: Re-configure as a Web server

If you can re-connect the server where you synchronized the software and images to your LAN, then you can simply install Apache on it. Otherwise, you will need to provision a new server (see Option 2).

Installation of Apache is simple:

    yum -y install httpd

Skip to “Placing the Software”.

==== Option 2: Building a Repository Server

If you need to build a separate server to act as the repository server, install a new RHEL7 system with at least 110GB of space. On this repo server during the installation make sure you select “Basic Web Server”.

==== Placing the Software

If necessary, attach the external storage, and then copy/move the repository files into Apache’s root folder. Note that the below copy step should be substituted with move (mv) if you are repurposing the server you used to sync.

    cp -a /path/to/repos/* /var/www/html/
    chmod -R +r /var/www/html/repos
    restorecon -vR /var/www/html

Make sure to add the firewall rules:

    firewall-cmd --add-service=http
    firewall-cmd --reload

Now start and enable Apache:

    systemctl enable httpd
    systemctl start httpd

=== OpenShift Systems

==== Build Your Hosts

At this point you can perform the initial build of the hosts that will be part of the OpenShift environment. It is recommended to use the latest version of Red Hat Enterprise Linux and to perform a minimal installation. You will also want to pay attention to the other OpenShift-specific prerequisites, documented here:

link:./installation.adoc[OpenShift Playbooks: OpenShift Enterprise 3 Installation]

Once the hosts are initially built, the repositories can be set up.

==== Connecting The Repos

On all of the relevant systems that will need OpenShift software components, create the following repository definitions, replacing <ip of the server> with the IP or hostname of the Apache server hosting the software repositories (use the editor of your choice):

    vi /etc/yum.repos.d/ose.repo

Place the following text in the file:

    [rhel-7-server-rpms]
    name=rhel-7-server-rpms
    baseurl=http://<ip of the server>/repos/rhel-7-server-rpms
    enabled=1
    gpgcheck=0

    [rhel-7-server-extras-rpms]
    name=rhel-7-server-extras-rpms
    baseurl=http://<ip of the server>/repos/rhel-7-server-extras-rpms
    enabled=1
    gpgcheck=0

    [rhel-7-server-optional-rpms]
    name=rhel-7-server-optional-rpms
    baseurl=http://<ip of the server>/repos/rhel-7-server-optional-rpms
    enabled=1
    gpgcheck=0

    [rhel-7-server-ose-3.0-rpms]
    name=rhel-7-server-ose-3.0-rpms
    baseurl=http://<ip of the server>/repos/rhel-7-server-ose-3.0-rpms
    enabled=1
    gpgcheck=0

    [epel]
    name=epel
    baseurl=http://<ip of the server>/repos/epel
    enabled=0
    gpgcheck=0

==== Host Preparation

At this point, the systems are ready to continue to be prepared following the OpenShift documentation. See the following section:
https://access.redhat.com/documentation/en/openshift-enterprise/version-3.0/openshift-enterprise-30-installation-and-configuration/chapter-2-installing#host-preparation

Skip the section titled “Registering the Hosts” and start with “Managing Base Packages”.

=== OpenShift Installation

==== Import OpenShift Dockerized Components

You can simply scp the images from the sync server to the individual OpenShift hosts:

    scp /var/www/html/images/ose3-images.tar root@openshift.host.name:
    ssh root@openshift.host.name “DOCKERIMPORTCOMMAND”

If you prefer, you could use wget on each OpenShift host to fetch the tar file and then perform the Docker import command locally.

On one of the hosts that will cat as an OpenShift Master, copy and import the builder images:

    scp /var/www/html/images/ose3-builder-images.tar root@openshift.masterhost.name:
    ssh root@openshift.masterhost.name “DOCKERIMPORTCOMMAND”

==== Run OpenShift Installer

You may now follow the rest of the OpenShift installation instructions in the documentation. See the following section:

https://access.redhat.com/documentation/en/openshift-enterprise/version-3.0/installation-and-configuration/#advanced-installation

==== Create the Internal Docker Registry

You now need to create the internal Docker registry. See the following section of the documentation:

https://access.redhat.com/documentation/en/openshift-enterprise/version-3.0/installation-and-configuration/#deploying-a-docker-registry

=== Post-Installation Changes

In one of the previous steps, the S2I images were imported into the Docker daemon running on one of the OpenShift Master hosts. In a typical connected installation these images would be pulled from Red Hat’s registry on demand. Since the internet is not available to do this, the images must be made available in some other Docker registry.

OpenShift provides an internal registry for storing the images that are built as a result of the S2I process, but it can also be used to hold the S2I builder images. The following steps assume you did not customize the service IP subnet (172.30.0.0/16) or the Docker registry port (5000).

==== Re-tag S2I Builder Images

First, on the Master host where you imported the S2I builder images, obtain the service address of your docker registry that we installed on the master earlier:

    oc get service docker-registry -t '{{.spec.clusterIP}}{{"\n"}}'
172.30.69.44
    export REGISTRY=172.30.69.44

Next, tag all of the builder images before pushing them into the OpenShift Docker registry:

.Feedback or Contribution Needed
****
Need to verify version numbers below
****

    docker tag registry.access.redhat.com/jboss-amq-6/amq-openshift $REGISTRY:5000/openshift/amq-openshift
    docker tag registry.access.redhat.com/jboss-eap-6/eap-openshift $REGISTRY:5000/openshift/eap-openshift
    docker tag registry.access.redhat.com/jboss-webserver-3/tomcat7-openshift $REGISTRY:5000/openshift/tomcat7-openshift
    docker tag registry.access.redhat.com/jboss-webserver-3/tomcat8-openshift $REGISTRY:5000/openshift/tomcat8-openshift
    docker tag registry.access.redhat.com/openshift3/mongodb-24-rhel7 $REGISTRY:5000/openshift/mongodb-24-rhel7
    docker tag registry.access.redhat.com/openshift3/mysql-55-rhel7 $REGISTRY:5000/openshift/mysql-55-rhel7
    docker tag registry.access.redhat.com/openshift3/nodejs-010-rhel7 $REGISTRY:5000/openshift/nodejs-010-rhel7
    docker tag registry.access.redhat.com/openshift3/perl-516-rhel7 $REGISTRY:5000/openshift/perl-516-rhel7
    docker tag registry.access.redhat.com/openshift3/php-55-rhel7 $REGISTRY:5000/openshift/php-55-rhel7
    docker tag registry.access.redhat.com/openshift3/postgresql-92-rhel7 $REGISTRY:5000/openshift/postgresql-92-rhel7
    docker tag registry.access.redhat.com/openshift3/python-33-rhel7 $REGISTRY:5000/openshift/python-33-rhel7
    docker tag registry.access.redhat.com/openshift3/ruby-20-rhel7 $REGISTRY:5000/openshift/ruby-20-rhel7

==== Create an Administrative User

In order to be able to push the Docker images into OpenShift’s Docker registry, you will need a user with sufficient privileges. Because the default OpenShift system administrator does not have a standard authorization token, it cannot to use to login to the Docker registry.

Create a new user account in whatever authentication system you are using with OpenShift. For example, if you are using local htpasswd-based authentication:

    htpasswd -b /etc/openshift/openshift-passwd adminuser <yourpasswd>

OpenShift does not create an “account” for the user just because the external authentication system has an acconunt. A user must log-in to OpenShift before an account is actually created in the itnternal database. You must log-in to OpenShift for this account to be created. This assumes you are using the self-signed certificates generated by OpenShift during the installation:

    oc login --certificate-authority=/etc/openshift/master/ca.crt -u adminuser https://openshift.master.host:8443

Get the user’s authentication token:

    MYTOKEN=$(oc whoami -t)
    echo $MYTOKEN

==== Modify the Security Policies

Since you have now switched the user associated with the host’s root system account, you must re-log-in as the OpenShift system administrator in order to make policy changes:

    oc login -u system:admin

Remember, the “login” command merely changes the account credentials that the CLI is using to communicate with OpenShift’s API.

In order to push images into the OpenShift Docker registry, an account must have the image-builder security role. Add this to your admin user:

    oadm policy add-role-to-user system:image-builder adminuser

Next, add the admin (administrative) role to the user in the special “openshift” project. This will allow the admin user to be able to edit the “openshift” project - in this case, to push the Docker images.

    oadm policy add-role-to-user admin adminuser -n openshift

==== Edit the Image Stream Definitions

The “openshift” project is where all of the imagestreams for builder images are created by the installer. They are loaded by the installer from the /usr/share/openshift/examples folder. Since we need to change all of the definitions, we will first delete what has been loaded into OpenShift’s database and then re-create them.

First, delete the existing imagestreams:

    oc delete is -n openshift --all

Make a backup of the files in /usr/share/openshift/examples/image-streams if you desire. Next, edit the file image-streams-rhel7.json in  /usr/share/openshift/examples/image-streams folder. You will find an imagestream section for each of the builder images. Edit the “spec” stanza to point to your internal docker registry. For example

    "spec": {
        "dockerImageRepository": "registry.access.redhat.com/openshift3/mongodb-24-rhel7",

would change to

    "spec": {
        "dockerImageRepository": "172.30.69.44:5000/openshift/mongodb-24-rhel7",

Repeat this for every imagestream in the file. Make sure you use the correct IP address that you determined earlier. When you are finished, save and exit. Repeat the same process for the JBoss imagestreams in jboss-image-streams.json

Now, load the updated imagestream definitions:

    oc create -f image-streams-rhel7.json -n openshift
    oc create -f jboss-image-streams.json -n openshift

==== Load the Docker Images

At this point the system has been prepared for loading the Docker images. First, log in to the Docker registry using the token and registry service IP obtained earlier:

    docker login -u adminuser -e mailto:adminuser@abc.com \
        -p $MYTOKEN $REGISTRY:5000

Next, push the Docker images:

.Feedback or Contribution Needed
****
Need to verify version numbers below
****

    docker push $REGISTRY:5000/openshift/amq-openshift
    docker push $REGISTRY:5000/openshift/eap-openshift
    docker push $REGISTRY:5000/openshift/tomcat7-openshift
    docker push $REGISTRY:5000/openshift/tomcat8-openshift
    docker push $REGISTRY:5000/openshift/mongodb-24-rhel7
    docker push $REGISTRY:5000/openshift/mysql-55-rhel7
    docker push $REGISTRY:5000/openshift/nodejs-010-rhel7
    docker push $REGISTRY:5000/openshift/perl-516-rhel7
    docker push $REGISTRY:5000/openshift/php-55-rhel7
    docker push $REGISTRY:5000/openshift/postgresql-92-rhel7
    docker push $REGISTRY:5000/openshift/python-33-rhel7
    docker push $REGISTRY:5000/openshift/ruby-20-rhel7

Verify the that all the imagestreams now have the tags populated and you will be good to go.

    oc get imagestreams -n openshift

As an example, one of the output should have tags as shown below

    NAME                                 DOCKER REPO                                                      TAGS                                     UPDATED
    jboss-amq-6                          registry.access.redhat.com/jboss-amq-6/amq-openshift             6.2-140,6.2-84,latest + 2 more...        10 days ago

The tags (6.2-140,6.2-84,latest + 2 more...) should not be empty.

=== Finishing Touches

At this point the OpenShift environment is almost ready for use. It is likely that you will want to install and configure a router, documented here:

https://access.redhat.com/documentation/en/openshift-enterprise/version-3.0/installation-and-configuration/#deploying-a-router

Other than that, your OpenShift environment is ready for use.

=== Optional: Quickstart Examples

To use any of the out of the box quickstart examples with OpenShift, you will need to clone the source code for them out of GitHub into an internal Git repository readable by all system users. *Quickstart templates will need to be updated to reflect the newly created internal Docker image and internal Git source locations.*

== Dealing with Corporate Web Proxies

.Feedback or Contribution Needed
****
Need to add a discussion of approach for handling corporate proxies.
****
