= Documentation Site for OpenShift Playbooks

OpenShift Playbooks is a documentation site for OpenShift, maintained by the OpenShift community and moderated by the North America Emerging Technologies Practice in Red Hat Consulting.

== Overview

This site is written in asciidoc format and is built using the link:https://github.com/asciidoctor/jekyll-asciidoc[Asciidoctor plugin for Jekyll].

== Contribution

=== Quickstart Guide using Docker

1. Clone git repositories
+
----
git clone https://github.com/redhat-cop/openshift-playbooks.git
----
2. Start Site Builder Container
+
----
cd openshift-playbooks
docker run \
  -u `id -u` -it \
  -v $PWD/:/home/jekyll/src/:Z \
  -p 4000:4000 \
  redhatcop/jekyll-local-builder
----
3. Launch browser and navigate to `http://localhost:4000`

=== Quickstart Guide using RHEL (or derivatives)

1. Install necessary packages.
+
----
sudo yum install -y libyaml-devel autoconf gcc-c++ readline-devel zlib-devel libffi-devel openssl-devel automake libtool bison sqlite-devel
----
1. Install Node.js Version Manager (nvm -- see https://github.com/creationix/nvm)
+
----
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
----
1. link:https://rvm.io/[Install RVM]
+
NOTE: For `gnome-terminal` users, you'll need to do this link:https://rvm.io/integration/gnome-terminal[additional step]
2. Install and use Ruby 2.0
+
----
rvm install 2.3.0
rvm use 2.3.0
----
3. Install and set up RubyGems
+
----
rvm rubygems latest
----
4. Install bundler
+
----
gem install bundler
----
5. Install project dependencies
+
----
bundle install
----
6. Build site source
+
----
bundle exec jekyll build
----
7. Run local Jekyll server to view site
+
----
bundle exec jekyll serve
----

=== Further Development

See our full link:./development_guide.adoc[contribution guide] for more details
