---
---
= Playbook Style Guide
Eric Sauer <esauer@redhat.com>
:toc: macro
:toc-title:

toc::[]

== Starting a New Document

All playbook guides should begin with a top-level heading and, at minimum, the following metadata:
----
---
---
= Top Level Heading
Author Name <author.email@mail.com>
:toc: macro
:toc-title:

toc::[]
----

== Content Best Practices

=== Links

Links between documents should follow the following format:
----
link:/path/to/file{outfilesuffix}[Link Name]
----
The `{outfilesuffix}` parameter should replace the file type and is there to handle the translation from '.adoc' to '.html' when we publish this content to our web front end.


== Requesting Feedback

If there are specific places where you'd like to request feedback or expansion from the community, we encourage you to call that out in your playbooks. Please use the following format:

----
.Feedback or Contribution Needed
****
This is a block where we would put a request for feedback or additional detail.
****
----

This will render as...

.Feedback or Contribution Needed
****
This is a block where we would put a request for feedback or additional detail.
****
