== LDAP Integration
Jamie Whetsell <jwhetsel@redhat.com>

=== References
https://docs.openshift.com/enterprise/3.0/admin_guide/configuring_authentication.html#LDAPPasswordIdentityProvider[OpenShift LDAP Authentication Reference]

https://docs.openshift.com/enterprise/3.1/install_config/syncing_groups_with_ldap.html[Syncing LDAP Groups]

http://ldapwiki.willeke.com/wiki/LDAP%20Query%20Examples[LDAP Query Examples]

=== What is LDAP
LDAP is a database organized in a Tree Structure.  LDAP is made up of standardaized objects with inheritance to include additional fields to that object.

Example
[source,ldap]
+ dc=example,dc=com # domain/organization
  + dn: ou=Users,dc=example,dc=com  # dn (distinguished name, unique key for each entry in LDAP, ou is organization unit)
    + dn: cn=jamie,ou=Users,dc=scires,dc=com (User entry dn)
      o: posixAccount
      cn: jamie whetsell
      mail: jwhetsel@redhat.com
      surName: Whetsell
      givenName: jamie
      phone: 843-867-5309
      ...  # based on what type of object they are using for the account
  + dn: ou=Groups,dc=sample,dc=com
    + dn: cn=admins,ou=Groups,dc=sample,dc=com
      member: cn=jamie,ou=Users,dc=example,dc=com  # This is a pointer to the dn of a user.  This says the user is in the admin groups
      member: cn=someotheruser,ou=Users,dc=example,dc=com
    + dn: cn=jamie,ou=Users,dc=example,dc=com
      member: cn=jamie,ou=Users,dc=example,dc=com # users can be members of multiple groups
      
      
=== Useful LDAP Queries

Active Directory
[source,ldap]
(&(objectClass=user)(sAMAccountName=yourUserName)
  (memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com))
  
LDAP
[source,ldap]
(&(objectClass=user)(cn=yourUserName)
  (memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com))

==== Configure Openshift for LDAP/AD

{source,ldap}
oauthConfig:
  ...
  identityProviders:
  - name: "my_ldap_provider" 
    challenge: true 
    login: true 
    provider:
      apiVersion: v1
      kind: LDAPPasswordIdentityProvider
      attributes:
        id: 
        - dn # the unique id of the user, this is being mapped to the dn field in ldap
        email: 
        - mail # users email that is being mapped
        name: 
        - cn  # This is the display name it is mapped to the cn(common name field in LDAP)
        preferredUsername: 
        - uid # this is the field that is the username when logging into open shift
      bindDN: "" # If the ldap has anonymous bind turned off, you may need to add a username and password to search for users
      bindPassword: "" 
      ca: my-ldap-ca-bundle.crt # This should be provided to you
      insecure: false # by default the system will try to use TLS for authentication
      url: "ldap://ldap.example.com/ou=Users,dc=example,dc=com?uid" # by default this is the ldap URI, it contains the ip address, search base (ou=Users,example,dc=com) and the user field you are using.  in this case uid
      

Adding a filter to a specific group



* item 1
* item 2

[source,ruby]
puts "Hello, World!"


