== LDAP Integration
Jamie Whetsell <jwhetsel@redhat.com>

=== References
https://docs.openshift.com/enterprise/3.0/admin_guide/configuring_authentication.html#LDAPPasswordIdentityProvider[OpenShift LDAP Authentication Reference]

https://docs.openshift.com/enterprise/3.1/install_config/syncing_groups_with_ldap.html[Syncing LDAP Groups]

http://ldapwiki.willeke.com/wiki/LDAP%20Query%20Examples[LDAP Query Examples]

http://www.openldap.org/faq/data/cache/185.html[Configuring OpenLDAP TLS]


==== Configure Openshift for LDAP/AD

[source,yaml]
  identityProviders:
  - name: "my_ldap_provider" 
    challenge: true 
    login: true 
    provider:
      apiVersion: v1
      kind: LDAPPasswordIdentityProvider
      attributes:
        id: 
        - dn # the unique id of the user, this is being mapped to the dn field in ldap
        email: 
        - mail # users email that is being mapped
        name: 
        - cn  # This is the display name it is mapped to the cn(common name field in LDAP)
        preferredUsername: 
        - uid # this is the field that is the username when logging into open shift
      bindDN: "" # If the ldap has anonymous bind turned off, you may need to add a username and password to search for users
      bindPassword: "" 
      ca: my-ldap-ca-bundle.crt # This should be provided to you
      insecure: false # by default the system will try to use TLS for authentication. setting to true will not use tls
      url: "ldap://ldap.example.com/ou=Users,dc=example,dc=com?uid" # by default this is the ldap URI, it contains the ip address, search base (ou=Users,example,dc=com) and the user field you are using.  in this case uid
      


=== What is LDAP
LDAP is a database organized in a Tree Structure.  LDAP is made up of standardaized objects with inheritance to include additional fields to that object.


Example
[source,ldap]
+ dc=example,dc=com # domain/organization
  + dn: ou=Users,dc=example,dc=com  # dn (distinguished name, unique key for each entry in LDAP, ou is organization unit)
    + dn: uid=jamie,ou=Users,dc=scires,dc=com (User entry dn)
      o: posixAccount
      cn: jamie whetsell
      uid: jamie
      mail: jwhetsel@redhat.com
      surName: Whetsell
      givenName: jamie
      phone: 843-867-5309
      ...  # based on what type of object they are using for the account
  + dn: ou=Groups,dc=sample,dc=com
    + dn: uid=admins,ou=Groups,dc=sample,dc=com
      member: uid=jamie,ou=Users,dc=example,dc=com  # This is a pointer to the dn of a user.  This says the user is in the admin groups
      member: uid=someotheruser,ou=Users,dc=example,dc=com
    + dn: uid=jamie,ou=Users,dc=example,dc=com
      member: uid=jamie,ou=Users,dc=example,dc=com # users can be members of multiple groups
      
      
=== Useful LDAP Queries

Active Directory
[source,ldap]
(&(objectClass=user)(sAMAccountName=yourUserName)
  (memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com))
  
LDAP
[source,ldap]
(&(objectClass=inetOrgPerson)(cn=uid)
  (memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com))

ApacheDS pre 2.1
[source,ldap]
(&(objectclass=groupOfNames)(cn=openshift)(member=cn=jamie,ou=People,dc=examplex,dc=com))

==== Adding a filter to a specific group

More than likely the logins to Openshift will be limited by a group.  This may include limiting the capabilities to certain groups.  We will discuss Group Syncing Later.

We will assume we are connection to a standard ldap.  The first step is to create a query to limit the user to a group, so from above we have:

[source,conf]
(&(objectClass=posixAccount)(memberof=CN=openshift,OU=groups,DC=example,DC=com))

so in english this looks like:

Where object class equals posixAccount and the user is a member of the openshift group.

==== Testing your LDAP queries

* You need to install the ldapsearch utils

[source,bash]
yum install openldap-clients -y

* Search for a user
[source,bash]
ldapsearch -D "uid=admin,ou=system" -h 172.17.84.3 -p 10389 -w secret -xZ -s base -b cn=openshift,ou=Users,dc=opentlc07a7,dc=com


* Search for groups
[source,bash]
ldapsearch -D "uid=admin,ou=system" -h 172.17.84.3 -p 10389 -w secret -x -sZ sub -b "dc=opentlc07a7,dc=com" "objectclass=groupOfNames"


* Get members of a group
[source,bash]
ldapsearch -D "uid=admin,ou=system" -h 172.17.84.3 -p 10389 -w secret -xZ -s base -b cn=openshift,ou=Groups,dc=opentlc07a7,dc=com

** Issues you May See with LDAP Search
_TLS: can't accept: TLS error -12195:Peer does not recognize and trust the CA that issued your certificate.._

[source,bash]
Modify your /etc/openldap/ldap.conf
TLS_CACERTDIR   /etc/openldap/certs # change to your cert dir
TLS_CACERT      /etc/openldap/certs/ca.cert.pem # use the ca issuer cert

** Issues with Openshift

_Problem_
[source,bash]
atomic-openshift-master[8827]: F1207 12:55:23.250834 8827
auth.go:114] error loading cert pool from ca file
/etc/pki/tls/certs/ca-bundle.crt: error reading
/etc/pki/tls/certs/ca-bundle.crt: x509: negative serial number

_Answer_
[source,bash]
Your CA cert from open ldap was not generated correctly.  It appears if you use the default CA this is an issue.  Create your own CA if possible.


==== Group Syncing with LDAP

Openshift allows for automatic syncing of groups from LDAP Server.  Generally you will not want to sync the entire LDAP.  So you must specify a user defined group.

[source,yaml]
kind: LDAPSyncConfig
apiVersion: v1
url: ldap://10.3.9.248
insecure: false
bindDN: "cn=Manager,dc=opentlcx,dc=com"
bindPassword: "password"
ca: /etc/openldap/certs/ca.cert.pem
groupUIDNameMapping:
    "cn=openshift,ou=Group,dc=opentlcx,dc=com": Users
    "cn=osadmins,ou=Group,dc=opentlcx,dc=com": Administrators
rfc2307:
    groupQuery:
        baseDN: "ou=Group,dc=opentlcx,dc=com"
        scope: sub
        derefAliases: never
        filter: (objectclass=groupOfNames)
    groupUIDAttribute: dn
    groupNameAttributes: [ cn ]
    groupMembershipAttributes: [ member ]
    usersQuery:
        baseDN: "ou=users,dc=opentlcx,dc=com"
        scope: sub
        derefAliases: never
        filter: (objectclass=inetOrgPerson)
    userUIDAttribute: dn
    userNameAttributes: [ cn ]
    
    * Errors *
    
    _Here the error: error: validation of LDAP sync config failed: groupsQuery.filter: invalid value '', Details: invalid query filter: LDAP Result Code 201 "": ldap: filter does not start with an '('_
    
    [source,bash]
    Still researching
