== LDAP Integration
Jamie Whetsell <jwhetsel@redhat.com>

=== References
https://docs.openshift.com/enterprise/3.0/admin_guide/configuring_authentication.html#LDAPPasswordIdentityProvider[OpenShift LDAP Authentication Reference]

https://docs.openshift.com/enterprise/3.1/install_config/syncing_groups_with_ldap.html[Syncing LDAP Groups]

http://ldapwiki.willeke.com/wiki/LDAP%20Query%20Examples[LDAP Query Examples]

=== What is LDAP
LDAP is a database organized in a Tree Structure.  LDAP is made up of standardaized objects with inheritance to include additional fields to that object.

Example
[source,ldap]
+ dc=example,dc=com # domain/organization
  + dn: ou=Users,dc=example,dc=com  # dn (distinguished name, unique key for each entry in LDAP, ou is organization unit)
    + dn: cn=jamie,ou=Users,dc=scires,dc=com (User entry dn)
      o: posixAccount
      cn: jamie
      mail: jwhetsel@redhat.com
      surName: Whetsell
      ...  # based on what type of object they are using for the account
  + dn: ou=Groups,dc=sample,dc=com
    + dn: cn=admins,ou=Groups,dc=sample,dc=com
      member: cn=jamie,ou=Users,dc=example,dc=com  # This is a pointer to the dn of a user.  This says the user is in the admin groups
      member: cn=someotheruser,ou=Users,dc=example,dc=com
    + dn: cn=jamie,ou=Users,dc=example,dc=com
      member: cn=jamie,ou=Users,dc=example,dc=com # users can be members of multiple groups
      
      
=== Useful LDAP Queries

Active Directory
[source,ldap]
(&(objectClass=user)(sAMAccountName=yourUserName)
  (memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com))
  
LDAP
[source,ldap]
(&(objectClass=user)(cn=yourUserName)
  (memberof=CN=YourGroup,OU=Users,DC=YourDomain,DC=com))

== First Section

* item 1
* item 2

[source,ruby]
puts "Hello, World!"


